### PR TITLE
Update runtime to 5.13

### PR DESCRIPTION
**Pull request by LeandroStanger**
https://github.com/flathub/net.meijn.onvifviewer/issues/10

### CODE REVIEW

**Comment by caspermeijn** [comment]
@LeandroStanger Have you tested the new build?

**Comment by LeandroStanger** [comment]
bot, build

**Comment by caspermeijn** [comment]
@LeandroStanger I currently have no camera available. Have you seen video with this new build?

**Comment by caspermeijn** [comment]
Updated to Qt 5.13 as part of #12

**Pull request closed without merging**
